# Generated by Django 3.0.8 on 2020-07-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200720_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
