# Generated by Django 3.0.8 on 2020-07-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
